# Generated by Django 5.2.7 on 2025-10-30 19:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
